### ISSUE TITLE
How to execute training and inference in this project?

### ISSUE THREAD

**Issue by GY-Jeong** [rbqlsquf/XAI_rationale-inference-LLM#4]
Hi,

I’m working with this project, but I’m unsure how to properly execute the training and inference processes based on the file structure.

1. **Training**:  
   - How should I run the training? Should I use `train.ipynb`, `run_train.sh`, or another file?  
   - Are there any specific configurations or dependencies I need to set up before running the training?

2. **Inference**:  
   - For inference, should I use `inference.ipynb` or `evaluation.py`?  
   - How do I load the trained model for inference, and what format should the input data have?

Also, is there any additional setup required (e.g., environment, dependencies)? I noticed a `requirements.txt` file—do I need to install specific packages?

Thanks in advance!

**Comment by GY-Jeong** [comment]
`ccfd`

**Comment by rbqlsquf** [comment]
Thank you for your questions! Here's a detailed guide on how to proceed with training and inference:

**1. Training:**

  To start the training process, simply run:
  

```
./run_train.sh
``` 

  This script will automatically begin the training process. If additional configuration is needed, check the `run_train.sh` file for environment variables or specific parameters.

**2. Inference**

  To run inference, execute the following command:
  
```
./run.sh
``` 
  This script will load the trained model and perform inference. For input format details or output file locations, refer to the comments inside the `run.sh` file.

**3. Installing Required Packages**

  All required packages are listed in `requirements.txt`. Install them by running:
```
pip install -r requirements.txt
``` 

We’re also working on a more detailed README and will provide it soon to clarify all setup and execution steps.

Let me know if you encounter any issues! 😊
