### ISSUE TITLE
Please upload the version information of the CUDA library used in the code and the GPU details.

### ISSUE THREAD

**Issue by pluto32** [rbqlsquf/XAI_rationale-inference-LLM#5]
Please upload the version information of the CUDA library used in the code and the GPU details.

**Comment by rbqlsquf** [comment]
Thank you for your suggestion!

Here are the version details of the CUDA library and GPU used in the code:

- NVIDIA-SMI: 470.182.03
- Driver Version: 470.182.03
- CUDA Version: 11.4

Let me know if you need additional environment or hardware details! 😊
