### ISSUE TITLE
Guidance Needed

### ISSUE THREAD

**Issue by kellya9510** [rbqlsquf/XAI_rationale-inference-LLM#6]
Could you please provide guidance on how to run this code?

**Comment by rbqlsquf** [comment]
Thank you for your question! Here’s how you can run the code:

**1. Training the Model**
To start the training process, run the following command:
```
./run_train.sh
``` 

This will automatically begin the training process. If additional configuration is needed, check the `run_train.sh` file for environment variables or specific parameters.

**2. Running Inference**
To perform inference with the trained model, run:
```
./run.sh
``` 
This script will load the trained model and execute inference. Refer to the comments inside the run.sh file for more details on input formats and output paths.

**3. Installing Dependencies**
Make sure to install all required packages listed in `requirements.txt` by running:
```
pip install -r requirements.txt
``` 
We are also working on updating the README file with more detailed setup and execution instructions. Stay tuned!

Let me know if you encounter any issues! 😊
